data_dir: /u/45/vanvlm1/unix/scratch_cs/csb/projects/enhancer_prediction/aaltorse/Data
#data_dir: Data
#cell_line: K562

# General configuration for extracting training data
window: 2000  # Profile window size
binSize: 100  # Resolution of the data

extract_enhancers:
  N: 1000               # Number of training data enhancers to extract
  distToPromotor: 2000  # Maximum distance to nearest promotor

extract_promoters:
  N: 1000               # Number of training promoters to extract
  between_TSS_distance: 2000

extract_random_pure:
  N: 1000               # Number of random regions to extract

define_random_with_signal:
  threshold: 5

create_training_data_combined:
  k: 5  # Number of folds to create for cross-validation

# Grid search parameters for finding an optimal C and G during SVM classification
cv_train_predict:
  # log2c: '-5,25,0.5'   # start,stop,step
  # log2g: '-25,10,0.5'  # start,stop,step
  log2c: '-3,3,1'  # start,stop,step
  log2g: '-3,3,1'  # start,stop,step
