channels:
  - conda-forge
  - bioconda

dependencies:
  # For preprocessing pipeline
  - r-base > 3.5
  - bowtie2
  - samtools
  - bedtools
  - phantompeakqualtools
  - bioconductor-rsamtools
  - bioconductor-genomeinfodb
  - bioconductor-genomeinfodbdata
  - snakemake
  - pandas

  # For train-predict
  - bioconductor-bsgenome.hsapiens.ucsc.hg19
  - r-optparse
